//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_DETAILS
    {
        public int DETAIL_ID { get; set; }
        public int EXAM_ID { get; set; }
        public int QUESTION_ID { get; set; }
    
        public virtual TBL_QUESTIONS TBL_QUESTIONS { get; set; }
        public virtual TBL_SETEXAM TBL_SETEXAM { get; set; }
    }
}
