//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_QUESTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_QUESTIONS()
        {
            this.Q_DETAILS = new HashSet<Q_DETAILS>();
        }
    
        public int QUESTION_ID { get; set; }
        [Display(Name = "Question Name")]
        [Required]
        public string Q_TEXT { get; set; }

        [Display(Name = "OptionA")]
        [Required]
        public string OPA { get; set; }
        [Display(Name = "OptionB")]
        [Required] public string OPB { get; set; }
        [Display(Name = "OptionC")]
        [Required] public string OPC { get; set; }
        [Display(Name = "OptionD")]
        [Required] public string OPD { get; set; }
        [Display(Name = "CorrectAnswer")]
        [Required] public string COP { get; set; }
        public Nullable<int> q_fk_catid { get; set; }
        [Display(Name = "QuestionLevel")]
        [Required]
        public string Q_level { get; set; }
    
        public virtual tbl_categroy tbl_categroy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Q_DETAILS> Q_DETAILS { get; set; }
    }
}
