//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SETEXAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SETEXAM()
        {
            this.Q_DETAILS = new HashSet<Q_DETAILS>();
        }
    
        public int EXAM_ID { get; set; }
        public Nullable<System.DateTime> EXAM_DATE { get; set; }
        public Nullable<int> EXAM_FK_STU { get; set; }
        public string EXAM_NAME { get; set; }
        public Nullable<int> EXAM_STD_SCORE { get; set; }
        public Nullable<System.TimeSpan> EXAM_DURATION { get; set; }
        public Nullable<int> EXAM_MARKS { get; set; }
        public Nullable<int> EXAM_NO_QUES { get; set; }
    
        public virtual TBL_STUDENT TBL_STUDENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Q_DETAILS> Q_DETAILS { get; set; }
    }
}
