//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_REPORT
    {
        public int TEST_ID { get; set; }

        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public int USER_SCORE { get; set; }
        public int MAX_MARKS { get; set; }
        public string USER_PAPER { get; set; }
    }
}
